Py39 eval failures? Need to double check on original

FAILED tests/debugpy/test_breakpoints.py::test_break_api[launch-breakpoint-code]
FAILED tests/debugpy/test_breakpoints.py::test_break_api[launch-debugpy.breakpoint-code]
FAILED tests/debugpy/test_django.py::test_django_template_exception_no_multiproc[launch] - assert [{'id': (0 <=...xEr...
FAILED tests/debugpy/test_breakpoints.py::test_break_api[attach_connect(cli)-debugpy.breakpoint-code]
FAILED tests/debugpy/test_breakpoints.py::test_break_api[attach_connect(cli)-breakpoint-code]

