Py39 eval failures? Need to double check on original

FAILED tests/debugpy/test_django.py::test_django_template_exception_no_multiproc[launch] - assert [{'id': (0 <=...xEr...
